### ISSUE TITLE
Bài 6 nòooo mn ơi

### ISSUE THREAD

**Issue by ZzThienKimzZ** [NguyenNgocKhanhVy/Lop-11A16-nhom-01#4]

**Comment by ZzThienKimzZ** [comment]
hiii =}}}}

**Comment by NgocHanhB16** [comment]
ê giờ phân chia mỗi người 2 câu nha

**Comment by NgocHanhB16** [comment]
câu 6 dài nên 1 người làm

**Comment by NguyenNgocKhanhVy** [comment]
Mn ơi, bài 7 câu mình chia mỗi người 1 câu nha. 2 câu cuối hơi khó nên mình thảo luận một chút nhé

**Comment by NgocHanhB16** [comment]
ok bà

**Comment by NguyenNgocKhanhVy** [comment]
Tui câu 3 nhoa

**Comment by Lkngann** [comment]
okok

**Comment by NguyenNgocKhanhVy** [comment]
Mn lựa câu của mình ik

**Comment by NgocHanhB16** [comment]
tui câu 2 nha

**Comment by Lkngann** [comment]
t câu 4 nha mn

**Comment by ZzThienKimzZ** [comment]
tuizz câu 1 với 2 heee

**Comment by NguyenNgocKhanhVy** [comment]
Mỗi người 1 câu @ZzThienKimzZ

**Comment by TranDongNghi** [comment]
z tui câu 5 nhak

**Comment by ZzThienKimzZ** [comment]
okee z tuiz câu 1 nhee

**Comment by ZzThienKimzZ** [comment]
eee mn oi mình lên giờ để thảo luận làm bài ii ? mai tui rảnh á mn sao?

**Comment by NguyenNgocKhanhVy** [comment]
Mk lm 9h45 tối t7 đc ko mn

**Comment by NguyenNgocKhanhVy** [comment]
Giờ đó chắc ai cũng rảnh mà hen?

**Comment by Lkngann** [comment]
Mn ơi tui thứ 7 tui rảnh nha, nên là chờ mn thuiii

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: NgoTranThienKim ***@***.***>
Đã gửi: Friday, November 5, 2021 10:34:37 PM
Đến: NguyenNgocKhanhVy/Lop-11A16-nhom-01 ***@***.***>
Cc: Lê Kim Ngân ***@***.***>; Comment ***@***.***>
Chủ đề: Re: [NguyenNgocKhanhVy/Lop-11A16-nhom-01] Bài 6 nòooo mn ơi (Issue #4)


okee z tuiz câu 1 nhee

**Comment by Lkngann** [comment]
thứ 7 tui rảnh nha nên là tui đợi mn thuii

**Comment by ZzThienKimzZ** [comment]
oke vậy @NgocHanhB16 , @TranDongNghi oi mn rảnh giờ đó kh?

**Comment by ZzThienKimzZ** [comment]
[
![image](https://user-images.githubusercontent.com/91887254/140539102-0d27bcc4-6d4f-4822-88ae-2a2f17c45ea6.png)
](url)
 đây mới là thảo luận thật của nhóm con nha thầy =}}

**Comment by ZzThienKimzZ** [comment]
@Lkngann  vô nhận hàng =}}}}

**Comment by TranDongNghi** [comment]
H đó tui rảnh nhoa😊😊

**Comment by ZzThienKimzZ** [comment]
oke z chốt T7 9h45 tối nha mn, giờ ngủ iiii pp pp

**Comment by NgocHanhB16** [comment]
Tui cũng rảnh giờ đó

**Comment by ZzThienKimzZ** [comment]
zô nò mn

**Comment by NguyenNgocKhanhVy** [comment]
![received_700956000878205](https://user-images.githubusercontent.com/91885988/140613967-20918e15-2eca-4990-9ec5-347dd7ec02af.jpeg)

**Comment by NguyenNgocKhanhVy** [comment]
Câu 3 ở phần này đk mn

**Comment by ZzThienKimzZ** [comment]
ừmmm đúng á =}}}

**Comment by NgocHanhB16** [comment]
đúng rồi đó bà

**Comment by NgocHanhB16** [comment]
ê mn giúp tui phần vd tín hiệu analog với

**Comment by NguyenNgocKhanhVy** [comment]
Tín hiệu Analog là một tín hiệu tương tự được truyền theo dạng liên tục (không ngắt quảng). Tôi lấy ví dụ : Khi chúng ta nghe một bản nhạc hoặc nghe tiếng chim hót, đó là một dạng của của tín hiệu Analog. Vì tín hiệu được truyền đi liên tục không ngắt quảng, tuy tần số có thay đổi theo biên độ khác nhau.

**Comment by Lkngann** [comment]
GND Viết tắt của Gound. Có một số chân GND trên Arduino, có thể sử dụng bất kỳ chân nào để nối đất cho mạch.
câu trả lời câu 4 t tìm đc nè, coi giúp t ikk

**Comment by NguyenNgocKhanhVy** [comment]
Arduino UNO có thể được cấp nguồn 5V thông qua cổng USB hoặc cấp nguồn ngoài với điện áp khuyên dùng là 7-12V DC và giới hạn là 6-20V.

**Comment by NguyenNgocKhanhVy** [comment]
Câu 5 nè đúng ko mn

**Comment by TranDongNghi** [comment]
chắc đúng ak

**Comment by ZzThienKimzZ** [comment]
@NgocHanhB16 tuiz nghĩ là vd về analog là cảm biến nhiệt độ, cảm biến độ ẩm nha

**Comment by NgocHanhB16** [comment]
ok Kim

**Comment by NguyenNgocKhanhVy** [comment]
Điện trở được hiểu khái quát là sự cản trở dòng điện của một vật dẫn điện. ... Trong thực tế, điện trở là một linh kiện điện tử thụ động gồm 2 tiếp điểm kết nối. Thường được dùng để hạn chế cường độ dòng điện chạy trong mạch. Điều chỉnh mức độ tín hiệu, dùng để chia điện áp.

**Comment by NguyenNgocKhanhVy** [comment]
Câu 7 ak mn

**Comment by NguyenNgocKhanhVy** [comment]
Mà nó ko đc rõ ràng lắm

**Comment by Lkngann** [comment]
Điện trở có mặt ở mọi nơi trong thiết bị điện tử và như vậy điện trở là linh kiện quan trọng không thể thiếu được , trong mạch điện , điện trở có những tác dụng sau :

Khống chế dòng điện qua tải cho phù hợp, Ví dụ có một bóng đèn 9V, nhưng ta chỉ có nguồn 12V, ta có thể đấu nối tiếp bóng đèn với điện trở để sụt áp bớt 3V trên điện trở.
Mắc điện trở thành cầu phân áp để có được một điện áp theo ý muốn từ một điện áp cho trước.
Phân cực cho bóng bán dẫn hoạt động
Tham gia vào các mạch tạo dao động R C
Điều chỉnh cường độ dòng điện đi qua các thiết bị điện.
Tạo ra nhiệt lượng trong các ứng dụng cần thiết.
Tạo ra sụt áp trên mạch khi mắc nối tiếp

**Comment by NguyenNgocKhanhVy** [comment]
Ai có câu trl rõ hơn ko

**Comment by Lkngann** [comment]
Xem giùm t với

**Comment by NguyenNgocKhanhVy** [comment]
Ukm ổn ak

**Comment by NguyenNgocKhanhVy** [comment]
V câu 7 ghi của ngân vào nha

**Comment by ZzThienKimzZ** [comment]
tuiz nghĩ câu trả của câu 6 là:
- Đèn không thể sáng bình thường vì arduino cung cấp nguồn điện từ  5-3.3V mà đèn led có hiệu điện thế dao động từ 1,9-3,2 vôn nên đèn sẽ sáng mạnh, dễ cháy ( vì 5-3.3V > 1,9-3,2V ). 
=> Cần mắc thêm thiết bị hỗ trợ là:  điện trở để giảm đòng điện đi qua bóng đèn

**Comment by Lkngann** [comment]
t add vô rồi nha

**Comment by NgocHanhB16** [comment]
Câu 6: Khi dòng điện của đèn led vượt quá hoặc thấp hơn điện áp định mức sẽ khiến đèn không hoạt động hoặc nhanh bị hỏng. Thiết bị hỗ trợ là điện trở. Này là ý của tui

**Comment by NgocHanhB16** [comment]
1.2 Điện áp định mức của đèn led
Đây là mức nguồn điện cần được cung cấp cho đèn để hoạt động bình thường. 
Mỗi một thiết bị đèn led sẽ có một định mức khác nhau. 
Sau khi chip led được cung cấp dòng điện đúng theo yêu cầu của nhà sản xuất đưa ra, đèn led sẽ chiếu sáng tốt nhất. 
Khi dòng điện của đèn led vượt quá hoặc thấp hơn điện áp định mức sẽ khiến đèn không hoạt động hoặc nhanh bị hỏng.
Do vậy, các nhà sản xuất luôn ghi rõ điện định mức của đèn led. Từ đó, người mua có thể nắm được mức thông số cần thiết nhằm đảm bảo đèn chiếu sáng tốt nhất.
1.3 Điện áp làm việc của đèn led
Đây là mức điện áp có thể giúp đèn led chiếu sáng được; Có thể lớn hơn hoặc bằng điện định mức của đèn led. 
Khi mức điện làm việc của đèn led bằng định mức có thể giúp đèn led hoạt động tốt. 
Điều này không ảnh hưởng đến độ bền và tuổi thọ của đèn.
Trong trường hợp mức điện làm việc cao hơn hoặc thấp hơn định mức; đèn led sẽ có thể bị hỏng hoặc khiến tuổi thọ đèn led thấp hơn.

**Comment by NguyenNgocKhanhVy** [comment]
Của hạnh được hơn ak

**Comment by ZzThienKimzZ** [comment]
eee nhma tuiz nghĩ mình phải trl rõ ra ấy, tại đề hỏi " đèn có sáng bthg humm "

**Comment by NguyenNgocKhanhVy** [comment]
Hừm v bà có ý j bổ sung vô ko

**Comment by NgocHanhB16** [comment]
Bà cứ bổ sung thêm câu trl của bà đi Kim

**Comment by NguyenNgocKhanhVy** [comment]
Nhắn lên đây tụi tui xem thử ik

**Comment by ZzThienKimzZ** [comment]
mà mn thấy đúng hong á

**Comment by ZzThienKimzZ** [comment]
ở trênnn đóooo @NguyenNgocKhanhVy =}} m lướt lên chút

**Comment by NgocHanhB16** [comment]
Câu của bà được đó Kim

**Comment by NguyenNgocKhanhVy** [comment]
Ừ v nhập của kim vô nha

**Comment by NgocHanhB16** [comment]
Mn chốt câu của Kim nha

**Comment by NguyenNgocKhanhVy** [comment]
Vậy kim nhập vô nha

**Comment by Lkngann** [comment]
Kim nhập đáp án vô iiii

**Comment by ZzThienKimzZ** [comment]
oke để tuiz nhập vào 🤘👌👽
