### ISSUE TITLE
Thảo luận về tinkercad

### ISSUE THREAD

**Issue by NguyenNgocKhanhVy** [NguyenNgocKhanhVy/Lop-11A16-nhom-01#5]

**Comment by ZzThienKimzZ** [comment]
eee chạy deadline tin kìa =}}

**Comment by ZzThienKimzZ** [comment]
trc T4 á

**Comment by NguyenNgocKhanhVy** [comment]
Bik gòi nèeee

**Comment by NguyenNgocKhanhVy** [comment]
Mà mấy h mk lm thì đc ha mn

**Comment by Lkngann** [comment]
Mình làm cái đèn nhấp nháy hôm bữa thầy nói đúng ko

**Comment by NgocHanhB16** [comment]
mai học xong tiết 3 đi

**Comment by NguyenNgocKhanhVy** [comment]
Đúng gòi nà

**Comment by NgocHanhB16** [comment]
đèn giao thông ngân ơi

**Comment by Lkngann** [comment]
Ờ ok

**Comment by NguyenNgocKhanhVy** [comment]
R chừng nào lm mn chốt h đi nà

**Comment by NguyenNgocKhanhVy** [comment]
9h15 tối mai có ai bận ko?

**Comment by TranDongNghi** [comment]
không ak

**Comment by ZzThienKimzZ** [comment]
hong á

**Comment by NgocHanhB16** [comment]
tui ko có bận

**Comment by Lkngann** [comment]
T ko bận á

**Comment by NguyenNgocKhanhVy** [comment]
Vậy chốt h đó ha

**Comment by TranDongNghi** [comment]
okiiiiiiii

**Comment by NguyenNgocKhanhVy** [comment]
Mn về tìm hiểu trc nha r có j mai mk thảo luận nhe

**Comment by ZzThienKimzZ** [comment]
okok =}}}}

**Comment by Lkngann** [comment]
Trên notion có tài liệu á, mn lên đó xem ik rồi mai làm :)))

**Comment by NgocHanhB16** [comment]
ok

**Comment by NguyenNgocKhanhVy** [comment]
Chốt 9h15 mai nha mn

**Comment by NguyenNgocKhanhVy** [comment]
Bye bye nhoa

**Comment by Lkngann** [comment]
Okok

**Comment by ZzThienKimzZ** [comment]
uhm okeee z nha, baiww mn ngủ ngon =}}}}

**Comment by TranDongNghi** [comment]
oki bai bai mn

**Comment by NgocHanhB16** [comment]
ok

**Comment by Lkngann** [comment]
Pái pai mụi người

**Comment by ZzThienKimzZ** [comment]
hello =}}}}

**Comment by Lkngann** [comment]
thảo luận nèo mụi người

**Comment by NguyenNgocKhanhVy** [comment]
A nhô lm nè mn ơi

**Comment by TranDongNghi** [comment]
làm seo zo mụi ngừi????????

**Comment by NguyenNgocKhanhVy** [comment]
Nối đại thử xem nó như nào he?

**Comment by ZzThienKimzZ** [comment]
vào b6 có code á =}}}

**Comment by NguyenNgocKhanhVy** [comment]
![Uploading received_174945458184482.jpeg…]()

**Comment by NguyenNgocKhanhVy** [comment]
Nối theo cái này nè

**Comment by ZzThienKimzZ** [comment]
giờ vô tinker lấy mạch vs Breadboard trc đi mn, òi viết code sau

**Comment by NgocHanhB16** [comment]
ê làm tương tự file bài 6 ấy rôig viết câu lệnh cho 3 đèn tương tự là xong

**Comment by NguyenNgocKhanhVy** [comment]
![Uploading 16369873322281064910790056574101.jpg…]()

**Comment by NguyenNgocKhanhVy** [comment]
V đúng ko mn

**Comment by TranDongNghi** [comment]
chắc đún ék

**Comment by Lkngann** [comment]
ờ đúng rùi á, giờ nối mấy cái dây nè

**Comment by ZzThienKimzZ** [comment]
thêm đèn zô nữa KZi

**Comment by NgocHanhB16** [comment]
thêm 3 cái điện trở nữa

**Comment by NgocHanhB16** [comment]
ê lắp 3 cái đèn đỏ phải ko

**Comment by NgocHanhB16** [comment]
ko có đèn xanh, vàng phải ko mn

**Comment by Lkngann** [comment]
tìm thử cái

**Comment by ZzThienKimzZ** [comment]
@NgocHanhB16 bà zô cái đèn Led á, cứ đưa nó vào ròi chỉnh màu sau, có hiện cái ô chỉnh màu í

**Comment by NguyenNgocKhanhVy** [comment]
Ê cái đường nối sao cho nó có màu khác bọt v

**Comment by ZzThienKimzZ** [comment]
trên thanh công cụ có cái ô màu đó KZi

**Comment by NguyenNgocKhanhVy** [comment]
![Uploading 16369886977745747859174424421999.jpg…]()

**Comment by NguyenNgocKhanhVy** [comment]
Nối v đk v mn

**Comment by TranDongNghi** [comment]
đúng rồi ak

**Comment by ZzThienKimzZ** [comment]
xong chưa

**Comment by ZzThienKimzZ** [comment]
qua code nè

**Comment by NguyenNgocKhanhVy** [comment]
Xong cái hình r nà

**Comment by NgocHanhB16** [comment]
bà xong rồi hả Kim

**Comment by TranDongNghi** [comment]
xog hình òi

**Comment by Lkngann** [comment]
ờ tui cũng xong rùi á

**Comment by NgocHanhB16** [comment]
tui cũng xong như hình rồi

**Comment by NguyenNgocKhanhVy** [comment]
Ê đánh code sao dị

**Comment by ZzThienKimzZ** [comment]
nhấp vào ô " Blocks " á, chỉnh sang Texte =}}

**Comment by Lkngann** [comment]
![image](https://user-images.githubusercontent.com/91885680/141807540-016bd9f5-a7e0-43bf-b7e2-a4041400686f.jpeg)

**Comment by Lkngann** [comment]
Cem giùm t với mn

**Comment by NguyenNgocKhanhVy** [comment]
Đúng r ak ngân

**Comment by TranDongNghi** [comment]
đúng rồi ak

**Comment by Lkngann** [comment]
ok cám ơn nhooooo

**Comment by TranDongNghi** [comment]
giờ tụi mik lm giống nhau nha

**Comment by TranDongNghi** [comment]
thảo luận chung cho nó dễ

**Comment by NgocHanhB16** [comment]
mình chọn R=13, G=11, Y=9 nha

**Comment by ZzThienKimzZ** [comment]
oke

**Comment by NguyenNgocKhanhVy** [comment]
Dô bài 6 xem xem cách lm thế nào đi mn

**Comment by ZzThienKimzZ** [comment]
uhm cop lại code í

**Comment by Lkngann** [comment]
mở đầu nè 
int R=13; int G=11; int Y=9

**Comment by ZzThienKimzZ** [comment]
Nãy giờ Hạnh vs Nghi mạng lag nên ít tương tác, vậy:
@NgocHanhB16 làm phần void setup 
@TranDongNghi  làm  loop dc hum?

**Comment by NgocHanhB16** [comment]
Phần thiết lập nè mn
void setup() {                
  pinMode(R, OUTPUT);
  pinMode(G, OUTPUT);
  pinMode(Y, OUTPUT);
}

**Comment by TranDongNghi** [comment]
void loop() {
  digitalWrite(R, HIGH);
  delay(2000);
  digitalWrite(R, LOW);
  delay(1000);  
  digitalWrite(G, HIGH);
  delay(2000); 
  digitalWrite(G, LOW);
  delay(1000);
  digitalWrite(Y, HIGH);
  delay(2000);          
  digitalWrite(Y, LOW);
  delay(1000);       
}

**Comment by NgocHanhB16** [comment]
phần thiết lập ghi dòng 3 nha mn

**Comment by TranDongNghi** [comment]
okok

**Comment by NguyenNgocKhanhVy** [comment]
R v bấm phần start simulation thử xem nó có hđ ko

**Comment by ZzThienKimzZ** [comment]
ê t có hiện đèn nè =}}}

**Comment by NguyenNgocKhanhVy** [comment]
Hoạt động ngon lành chứ hẻ

**Comment by TranDongNghi** [comment]
t cũng có hiện lun nek

**Comment by NgocHanhB16** [comment]
bên tui đèn cx sáng rồi

**Comment by ZzThienKimzZ** [comment]
> void loop() {
> digitalWrite(R, HIGH);
> delay(2000);
> digitalWrite(R, LOW);
> delay(1000);
> digitalWrite(G, HIGH);
> delay(2000);
> digitalWrite(G, LOW);
> delay(1000);
> digitalWrite(Y, HIGH);
> delay(2000);
> digitalWrite(Y, LOW);
> delay(1000);
> }

**Comment by NgocHanhB16** [comment]
@NguyenNgocKhanhVy tui mới xem lại hình của bà. Hình như tụi mình mắc sai rồi đó. Dòng điện phải qua điện trở rồi mới tới đèn chứ

**Comment by NguyenNgocKhanhVy** [comment]
Ụa v hả?

**Comment by NguyenNgocKhanhVy** [comment]
Để tui xem lại xem thế nào

**Comment by NguyenNgocKhanhVy** [comment]
Mn ơi, v cái mạch mình sửa sao nhỉ?

**Comment by Lkngann** [comment]
![image](https://user-images.githubusercontent.com/91885680/141895469-3d13001f-af6c-4e9b-97bb-4b114fd14df5.jpeg)

**Comment by Lkngann** [comment]
Ê mn , t mới sửa lại, xem giùm t

**Comment by TranDongNghi** [comment]
đúng r ak, t cũng sửa giống z ^^

**Comment by NguyenNgocKhanhVy** [comment]
@NgocHanhB16 @ZzThienKimzZ  sửa v đúng ko mấy bà

**Comment by NgocHanhB16** [comment]
ừ sủa vậy hợp lý hơn đó

**Comment by Lkngann** [comment]
![image](https://user-images.githubusercontent.com/91885680/141900711-eeb75da8-7170-4c63-b903-612ac63c4d00.jpeg)

**Comment by TranDongNghi** [comment]
đúng rồi ak t cũng sửa z

**Comment by NguyenNgocKhanhVy** [comment]
@NgocHanhB16 @ZzThienKimzZ sửa v đúng r đúng ko mấy bà

**Comment by NgocHanhB16** [comment]
ừ Ngân sửa vậy hợp lý hơn rồi

**Comment by ZzThienKimzZ** [comment]
@NguyenNgocKhanhVy uhm giờ thì mắc đr á

**Comment by NguyenNgocKhanhVy** [comment]
Oki v t sửa theo mấy bạn nhoa

**Comment by Lkngann** [comment]
Okok

**Comment by ZzThienKimzZ** [comment]
hiii =}
